name       : gnome-builder
version    : 3.28.2
release    : 39
homepage   : https://wiki.gnome.org/Apps/Builder
source     :
    - https://download.gnome.org/sources/gnome-builder/3.28/gnome-builder-3.28.2.tar.xz : 398baaf8b14407a666b9d9eddbe9bde0812a86479f534085080149bd3271372e
license    : GPL-2.0-or-later
component  : programming.ide
summary    : Gnome Builder
description: |
    Builder is a new IDE for GNOME that is focused on bringing the power of our platform to more developers than ever before.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(jsonrpc-glib-1.0)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mm-common-util)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(template-glib-1.0)
    - pkgconfig(vte-2.91)
    - desktop-file-utils
    - flatpak-devel
    - itstool
    - llvm-clang-devel
    - vala
rundeps    :
    - flatpak
    - gnome-code-assistance
    - python3-jedi
    - python-lxml
setup      : |
    %meson_configure -Dwith_spellcheck=false -Dwith_sysprof=false
build      : |
    %meson_build
install    : |
    %meson_install
