name       : gnome-builder
version    : 3.26.1
release    : 29
homepage   : https://wiki.gnome.org/Apps/Builder
source     :
    - https://download.gnome.org/sources/gnome-builder/3.26/gnome-builder-3.26.1.tar.xz : f9cbd537c9aac84019372a389caf868b6688f47279058d186a1a28b0d8245e29
license    : GPL-2.0
component  : programming.ide
summary    : Gnome Builder
description: |
    Builder is a new IDE for GNOME that is focused on bringing the power of our platform to more developers than ever before.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mm-common-util)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(template-glib-1.0)
    - pkgconfig(vte-2.91)
    - desktop-file-utils
    - flatpak-devel
    - itstool
    - llvm-clang-devel
    - vala
rundeps    :
    - platpak
    - gnome-code-assistance
    - python3-jedi
    - python-lxml
setup      : |
    %meson_configure -Dwith_sysprof=false
build      : |
    %meson_build
install    : |
    %meson_install
