name       : gnome-builder
version    : 3.24.1
release    : 22
homepage   : https://wiki.gnome.org/Apps/Builder
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-builder/3.24/gnome-builder-3.24.1.tar.xz : d0630dceeaf09285640ecec79545baf811321636a441824a9243e7f3a4467583
license    : GPL-2.0
component  : programming.ide
summary    : Gnome Builder
description: |
    Builder is a new IDE for GNOME that is focused on bringing the power of our platform to more developers than ever before.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mm-common-util)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(vte-2.91)
    - clang-devel
    - itstool
    - desktop-file-utils
rundeps    :
    - python3-jedi
    - python-lxml
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
