name       : gnome-builder
version    : 3.18.1
release    : 9
homepage   : https://wiki.gnome.org/Apps/Builder
source     :
    - https://download.gnome.org/sources/gnome-builder/3.18/gnome-builder-3.18.1.tar.xz : 501c95220dcf8ca44a5748e863492377fe2c3aee78a95973d6819b1836e5407c
license    : GPL-2.0
component  : editor
summary    : Gnome Builder
description: |
    Builder is a new IDE for GNOME that is focused on bringing the power of our platform to more developers than ever before.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - clang-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
