name       : gnome-builder
version    : '41.3'
release    : 77
homepage   : https://wiki.gnome.org/Apps/Builder
source     :
    - https://download.gnome.org/sources/gnome-builder/41/gnome-builder-41.3.tar.xz : e2250fc8e9e9f2002c452e5950d82685734d3c4480b35167ab508ac8702509e1
license    : GPL-2.0-or-later
component  : programming.ide
summary    : Gnome Builder
description: |
    Builder is a new IDE for GNOME that is focused on bringing the power of our platform to more developers than ever before.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(jsonrpc-glib-1.0)
    - pkgconfig(libcmark)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libportal)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mm-common-util)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(sysprof-4)
    - pkgconfig(template-glib-1.0)
    - pkgconfig(vte-2.91)
    - ctags
    - desktop-file-utils
    - itstool
    - llvm-clang-devel
    - vala
rundeps    :
    - ctags
    - flatpak
    - python-jedi
    - python-lxml
    - valgrind # Ensure the "run with valgrind" support works OOTB
setup      : |
    %meson_configure \
        -Dplugin_autotools=true \
        -Dplugin_cargo=true \
        -Dplugin_ctags=true \
        -Dplugin_devhelp=true \
        -Dplugin_flatpak=true \
        -Dplugin_gvls=true \
        -Dplugin_make=true \
        -Dplugin_meson=true \
        -Dplugin_spellcheck=true \
        -Dplugin_sysprof=true \
        -Dplugin_update_manager=false
build      : |
    %ninja_build
install    : |
    %ninja_install
