name       : gnome-builder
version    : 3.16.2
release    : 1
homepage   : https://wiki.gnome.org/Apps/Builder
source     :
    - https://download.gnome.org/sources/gnome-builder/3.16/gnome-builder-3.16.3.tar.xz : a1d7b287d39ce724114c128e25bb00e273ecd8982ed22c8aba48cad9c4d51e61
license    : GPL-2.0
summary    : Gnome Builder
builddeps  :
    - python3-devel
    - clang-devel
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gjs-internals-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(pygobject-3.0)
description: |
    Builder is a new IDE for GNOME that is focused on bringing the power of our platform to more developers than ever before.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
