name       : gnome-builder
version    : 3.40.0
release    : 65
homepage   : https://wiki.gnome.org/Apps/Builder
source     :
    - https://download.gnome.org/sources/gnome-builder/3.40/gnome-builder-3.40.0.tar.xz : 8814c42e622b73bc688efeb20c9751bf3488fc6751ea3ca9316a53e5289be279
license    : GPL-2.0-or-later
component  : programming.ide
summary    : Gnome Builder
description: |
    Builder is a new IDE for GNOME that is focused on bringing the power of our platform to more developers than ever before.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(jsonrpc-glib-1.0)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libportal)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mm-common-util)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(sysprof-4)
    - pkgconfig(template-glib-1.0)
    - pkgconfig(vte-2.91)
    - ctags
    - desktop-file-utils
    - itstool
    - llvm-clang-devel
    - vala
rundeps    :
    - ctags
    - flatpak
    - python3-jedi
    - python-lxml
    - valgrind # Ensure the "run with valgrind" support works OOTB
setup      : |
    %meson_configure \
        -Dplugin_autotools=true \
        -Dplugin_cargo=true \
        -Dplugin_ctags=true \
        -Dplugin_devhelp=true \
        -Dplugin_flatpak=true \
        -Dplugin_gvls=true \
        -Dplugin_make=true \
        -Dplugin_meson=true \
        -Dplugin_spellcheck=true \
        -Dplugin_sysprof=true \
        -Dplugin_update_manager=false
build      : |
    %meson_build
install    : |
    %meson_install
