name       : gnome-builder
version    : 3.34.1
release    : 53
homepage   : https://wiki.gnome.org/Apps/Builder
source     :
    - https://download.gnome.org/sources/gnome-builder/3.34/gnome-builder-3.34.1.tar.xz : 0b6e461057ea8151e80524c0ea7ef1cb948e92afda9dc6bd33ae3392f04501a4
license    : GPL-2.0-or-later
component  : programming.ide
summary    : Gnome Builder
description: |
    Builder is a new IDE for GNOME that is focused on bringing the power of our platform to more developers than ever before.
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(jsonrpc-glib-1.0)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(libpcre2-8)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(mm-common-util)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(template-glib-1.0)
    - pkgconfig(vte-2.91)
    - ctags
    - desktop-file-utils
    - flatpak-devel
    - itstool
    - llvm-clang-devel
    - vala
rundeps    :
    - ctags
    - flatpak
    - python3-jedi
    - python-lxml
setup      : |
    %meson_configure \
        -Dplugin_autotools=true \
        -Dplugin_cargo=true \
        -Dplugin_ctags=true \
        -Dplugin_devhelp=true \
        -Dplugin_flatpak=true \
        -Dplugin_make=true \
        -Dplugin_meson=true \
        -Dplugin_spellcheck=true \
        -Dplugin_sysprof=false \
        -Dplugin_vala=true
build      : |
    %meson_build
install    : |
    %meson_install
