name       : gnome-builder
version    : 3.20.4
release    : 15
homepage   : https://wiki.gnome.org/Apps/Builder
source     :
    - https://download.gnome.org/sources/gnome-builder/3.20/gnome-builder-3.20.4.tar.xz : b3e69495cd0fcfd3e3a7590f52aadaae7f45393eefd47ab5581a851cdd489041
license    : GPL-2.0
component  : programming.ide
summary    : Gnome Builder
description: |
    Builder is a new IDE for GNOME that is focused on bringing the power of our platform to more developers than ever before.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(vte-2.91)
    - clang-devel
    - itstool
    - desktop-file-utils
rundeps    :
    - python3-jedi
    - python-lxml
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
